export const MESSAGES = {
    STUDENT_CREATED: 'Student created successfully, OTP is sent to the email address.',
    OTP_SENT: 'OTP is sent to the email address.',
    INVALID_OTP: 'Invalid OTP.',
    OTP_VERIFIED: 'OTP verified successfully.',
    PASSWORD_MISMATCH: 'Passwords do not match.',
    STUDENT_NOT_FOUND: 'Student not found.',
    ADMIN_NOT_FOUND: 'Admin not found.',
    LOGIN_SUCCESS: 'Login successful.',
    LOGOUT_SUCCESS: 'Logout successful.',
    OTP_RESEND_FAIL: 'Failed to resend OTP.',
    INVALID_GOOGLE_TOKEN: 'Invalid Google ID token.',
    GOOGLE_SIGNIN_SUCCESS: 'Google sign-in successful.',
    ACCOUNT_BLOCKED: "You are blocked currently. Can't login.",
    EMAIL_REQUIRED: 'Google account must have an email.',
    GOOGLE_TOKEN_REQUIRED: 'Google ID token is required.',
    PASSWORD_RESET_LINK_SENT: 'Password reset link sent to registered email.',
    PASSWORD_RESET_ERROR: 'Error in sending link.',
    INTERNAL_SERVER_ERROR: 'Internal server error.',
    INVALID_REFRESH_TOKEN: 'Invalid or expired refresh token.',
    NO_REFRESH_TOKEN: 'No refresh token found.',
    REFRESH_TOKEN_SUCCESS: 'New access token generated successfully.',

    COURSE_NOT_FOUND:'Course not found',
    EDIT_PROFILE_SUCCESS:'Profile edited successfully',

    NO_STUDENTS_FOUND: "No students found",
    NO_TUTORS_FOUND: "No tutors found",
    TUTOR_NOT_FOUND: "Tutor not found",
    TUTOR_APPROVED_SUCCESS: "Tutor approved successfully",
    TUTOR_REJECTED_SUCCESS: "Tutor rejected and email sent.",
    COURSE_APPROVED_SUCCESS: "Course approved successfully",
    COURSE_REJECTED_SUCCESS: "Course application rejected",
    APPROVAL_EMAIL_SUBJECT: "Your Application Approved",
    REJECTION_EMAIL_SUBJECT: "Your Application Rejected",

    NO_CATEGORIES_FOUND: "No categories found",
    CATEGORY_ADDED_SUCCESS: "Category added successfully",
    VALID_CATEGORY_REQUIRED: "Valid Category name is required",
    CATEGORY_NOT_FOUND: "Category not found",
    CATEGORY_NAME_EXISTS: "Category name already exists",
    CATEGORY_UPDATED_SUCCESS: "Category updated successfully",

    COURSE_ADD_SUCCESS:'Courses added successfully',
    FAILED_FETCH_BESTSELLING: "Failed to fetch bestselling courses",

    LECTURES_ADDED_SUCCESS: "Lectures added successfully",
    LECTURE_NOT_FOUND: "Lecture not found",
    LECTURE_UPDATED_SUCCESS: "Lecture updated successfully",
    FILE_REQUIRED: "Video files are required for all lectures",
    INVALID_COURSE_ID: "Invalid courseId format",
    VIDEO_FILE_MISMATCH: "Each lecture must have a corresponding video file",

    PAYMENT_NOT_FOUND:'Payment not found',
    RATING_ADD_FAILED: "Failed to add rating to the course",
    RATING_FETCH_ERROR: "Error fetching ratings",
    MOST_RATED_COURSE_NOT_FOUND: "Most rated course not found",

}